version: '3.9'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api_music_catalog
    volumes:
      - .:/catalog_pr
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./catalog_pr/.env

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./catalog_pr/.env
    ports:
    - "15432:5432" 

volumes:
  postgres_data:
